### ISSUE TITLE
Wrong answer for 2-qubit non-Bell state

### ISSUE THREAD

**Issue by bernardyeszero** [KwiatQIM/Quantum-Tomography#39]
Dear developer,

Thanks for the tomography code. I find the code works fine with Bell state but produce the wrong answer for the non-Bell state. The attached file is an example. The counts are generated from qiskit simulation for a 2-qubit random circuit. 

[problem_example.pdf](https://github.com/KwiatLab/Quantum-Tomography/files/11937972/problem_example.pdf)

As the Input[6] and Outpu[6] show, the state can reproduce the counts. So, I'm not sure if the tomography code is not applicable for non-Bell states. Could you please help me check the problem?

Besides, I also tried three-particle tomography, I found there is a bug in Line 911 of TomoClass.py, the condition should be: elif(counts.shape[1] == 2**(self.conf['NQubits']))

Best regards,

Bernard

**Comment by timurjavid** [comment]
Hi @bernardyeszero,

Sorry for the late reply! I just noticed this issue was open.

Thank you for the feedback! I'll start looking into this.

Thanks,

Timur

**Comment by timurjavid** [comment]
Hi @bernardyeszero, can you also show the qiskit circuit you ran to obtain those counts?

For the fidelity part, it seems like you're calculating the fidelity with the bell state as the true state, however the input state is the approximated state from the circuit you said was random, so the fidelity should be (correctly) low, from what I understand.

**Comment by timurjavid** [comment]
@bernardyeszero Hi Bernard, sorry for the long wait time! I figured out the issue. I think it has to do with the way our python code currently handles data with `NDetectors = 2`. I'll work on trying to fix the issue in the library, but for now, you can use `NDetectors = 1` and instead extract the first value in each row of the counts (corresponding to the correct measurement vector).

I changed parts of your code to make it work. I mostly changed things in `DensityMatrixRe.dm()`. Let me know if you need more explanation for the workaround. I attached it here: 

[tomographyissue39.ipynb.zip](https://github.com/KwiatLab/Quantum-Tomography/files/12242517/tomographyissue39.ipynb.zip)

**Comment by timurjavid** [comment]
Hi @bernardyeszero, sorry for the late response! I spent way too long trying to figure out what the issue was. There are two main issues happening here, I think. 

The first is that our code is currently mishandling the case when `NDetectors = 2`, misshaping the input data. I made an issue (#40) and will work on fixing it. For now, you can use `NDetectors = 1` and "emulate" the data by doing a complete set of measurements as if you are only using one detector (measuring the opposite state). Meaning, if you measure |0>, also measure |1>. Qiskit still uses 2 detectors, however, so there will be lots of redundant data (144 counts instead of 36). In this case, you need to discard all but the first column of counts.

The second issue is that Qiskit reverses the ordering of the qubits, so |01> and |10> terms will be flipped in the density matrix. This causes the state fidelity to completely tank, which might explain partially why you were getting such low fidelities on anything besides Bell states, since Bell states would be unaffected by this issue. To translate between Qiskit and anything else, you need to do [`reverse_qargs()` ](https://qiskit.org/documentation/stubs/qiskit.quantum_info.DensityMatrix.html#qiskit.quantum_info.DensityMatrix.reverse_qargs) on the density matrix before you exchange between the two platforms. This was infuriating to find, since I thought it was initially something to do with our tomography code.

I attached a very modified version of your code below. Give it a try and let me know if you have any other issues. Thank you!

[tomographyissue39.ipynb.zip](https://github.com/KwiatLab/Quantum-Tomography/files/12261786/tomographyissue39.ipynb.zip)
